# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nframe3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from editedframe4 import Ui_Dialog4
import textwrap
import cv2
from fpdf import FPDF
from PIL import Image
import time
from PyQt5 import QtWidgets, uic
from PyQt5.QtWidgets import QFileDialog

class Ui_Dialog3(object):
    def setupUi(self, Dialog3):
        Dialog3.setObjectName("Dialog3")
        Dialog3.resize(1000, 600)
        Dialog3.setMaximumSize(QtCore.QSize(1000, 600))
        Dialog3.setWindowOpacity(1.0)
        Dialog3.setAutoFillBackground(False)
        self.widget = QtWidgets.QWidget(Dialog3)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1011, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 77, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 77, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 77, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 77, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 0, 171, 51))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(Dialog3)
        self.widget_2.setGeometry(QtCore.QRect(80, 100, 771, 431))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_2.setPalette(palette)
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(10, -10, 591, 51))
        self.label_2.setStyleSheet("font: 8pt \"STHupo\";")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.pushbutton3 = QtWidgets.QPushButton(self.widget_2)
        self.pushbutton3.setGeometry(QtCore.QRect(410, 380, 100, 40))
        self.pushbutton3.setObjectName("pushbutton3")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(20, 250, 161, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 161, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(10, 170, 221, 31))
        self.label_5.setObjectName("label_5")
        self.degreebox = QtWidgets.QTextEdit(self.widget_2)
        self.degreebox.setGeometry(QtCore.QRect(190, 70, 300, 31))
        self.degreebox.setObjectName("degreebox")
        self.label_6 = QtWidgets.QLabel(self.widget_2)
        self.label_6.setGeometry(QtCore.QRect(10, 110, 161, 31))
        self.label_6.setObjectName("label_6")
        self.gradbox = QtWidgets.QDateEdit(self.widget_2)
        self.gradbox.setGeometry(QtCore.QRect(230, 170, 141, 31))
        self.gradbox.setObjectName("gradbox")
        self.textEdit = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit.setGeometry(QtCore.QRect(190, 110, 301, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_2)
        self.textEdit_2.setGeometry(QtCore.QRect(190, 240, 371, 51))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(540, 140, 151, 61))
        self.pushButton.setObjectName("pushButton")
        self.widget.raise_()
        self.widget_2.raise_()
        self.label_6.raise_()

        self.retranslateUi(Dialog3)
        QtCore.QMetaObject.connectSlotsByName(Dialog3)
        self.pushButton.clicked.connect(self.open_file_dialog)
        self.pushbutton3.clicked.connect(self.fourthFrame)
        

        
        
    def open_file_dialog(self):
        file_path_, _ = QFileDialog.getOpenFileName(None, "Select Image","", "Image Files (*.png *.jpg *.jpeg)")#tuple unpacking
        if file_path_:
            # Load the image using Pillow
            image = Image.open(file_path_)
            # Perform any required operations with the image
            image.save("userinput.jpg")
            pixmap = QPixmap(file_path_)

    def fourthFrame(self):
        # connect 4th frame
        f = open("files/Degree.txt", 'w')
        f.write(self.degreebox.toPlainText())
        f.close()
        f = open("files/university.txt", 'w')
        f.write(self.textEdit.toPlainText())
        f.close()
        f = open("files/Graduationdate.txt", 'w')
        f.write(self.gradbox.text())
        f.close()
        f = open("files/EducationDescription.txt", 'w')
        f.write(self.textEdit_2.toPlainText())
        f.close()
        self.Dialog4 = QtWidgets.QDialog()
        self.ui = Ui_Dialog4()
        self.ui.setupUi(self.Dialog4)
        self.Dialog4.show()

    def retranslateUi(self, Dialog3):
        _translate = QtCore.QCoreApplication.translate
        Dialog3.setWindowTitle(_translate("Dialog3", "TalentMap"))
        self.label.setText(_translate("Dialog3", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; font-style:italic; color:#ffffff;\">TalentMap</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog3", "<html><head/><body><p><span style=\" font-size:22pt; color:#314da8;\">Enter Educational Qualification</span></p></body></html>"))
        self.pushbutton3.setText(_translate("Dialog3", "Next"))
        self.label_3.setText(_translate("Dialog3", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#314da8;\">Description :</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog3", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#314da8;\">Degree :</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog3", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#314da8;\">Graduation Date :</span></p></body></html>"))
        self.label_6.setText(_translate("Dialog3", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#314da8;\">University  :</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog3", "Upload Image"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog3 = QtWidgets.QDialog()
    ui = Ui_Dialog3()
    ui.setupUi(Dialog3)
    Dialog3.show()
    sys.exit(app.exec_())
