# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nFrame4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from nFrame5 import Ui_Dialog5

class Ui_Dialog4(object):
    def setupUi(self, Dialog4):
        Dialog4.setObjectName("Dialog4")
        Dialog4.resize(600, 350)
        Dialog4.setWindowOpacity(1.0)
        Dialog4.setAutoFillBackground(False)
        self.widget = QtWidgets.QWidget(Dialog4)
        self.widget.setGeometry(QtCore.QRect(0, 0, 600, 50))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 77, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 77, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 77, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(49, 77, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget.setPalette(palette)
        self.widget.setAutoFillBackground(True)
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 0, 171, 51))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.widget_2 = QtWidgets.QWidget(Dialog4)
        self.widget_2.setGeometry(QtCore.QRect(0, 50, 600, 300))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.widget_2.setPalette(palette)
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 471, 41))
        self.label_2.setStyleSheet("font: 8pt \"STHupo\";")
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName("label_2")
        self.pushButton4 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton4.setGeometry(QtCore.QRect(250, 250, 100, 40))
        self.pushButton4.setObjectName("pushButton4")
        self.descripbox = QtWidgets.QLineEdit(self.widget_2)
        self.descripbox.setGeometry(QtCore.QRect(180, 150, 401, 91))
        self.descripbox.setObjectName("descripbox")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 151, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget_2)
        self.label_4.setGeometry(QtCore.QRect(10, 60, 161, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget_2)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 211, 31))
        self.label_5.setObjectName("label_5")
        self.desigbox = QtWidgets.QTextEdit(self.widget_2)
        self.desigbox.setGeometry(QtCore.QRect(230, 60, 300, 31))
        self.desigbox.setObjectName("desigbox")
        self.companybox = QtWidgets.QTextBrowser(self.widget_2)
        self.companybox.setGeometry(QtCore.QRect(230, 110, 300, 30))
        self.companybox.setObjectName("companybox")

        self.retranslateUi(Dialog4)
        QtCore.QMetaObject.connectSlotsByName(Dialog4)

        self.pushButton4.clicked.connect(self.sixthscr)

    def sixthscr(self):
        self.Dialog5 = QtWidgets.QDialog()
        self.ui = Ui_Dialog5()
        self.ui.setupUi(self.Dialog5)
        self.Dialog5.show()

    def retranslateUi(self, Dialog4):
        _translate = QtCore.QCoreApplication.translate
        Dialog4.setWindowTitle(_translate("Dialog4", "TalentMap"))
        self.label.setText(_translate("Dialog4", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600; font-style:italic; color:#ffffff;\">TalentMap</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog4", "<html><head/><body><p><span style=\" font-size:22pt; color:#314da8;\">Enter Work Experience</span></p></body></html>"))
        self.pushButton4.setText(_translate("Dialog4", "Next"))
        self.label_3.setText(_translate("Dialog4", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#314da8;\">Description :</span></p></body></html>"))
        self.label_4.setText(_translate("Dialog4", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#314da8;\">Designation      :</span></p></body></html>"))
        self.label_5.setText(_translate("Dialog4", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#314da8;\">Company Name :</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog4 = QtWidgets.QDialog()
    ui = Ui_Dialog4()
    ui.setupUi(Dialog4)
    Dialog4.show()
    sys.exit(app.exec_())
