# Form implementation generated from reading ui file 'f:\1-2 semester\hackathonimproved\hackathonImprovised\nFrame5.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog5(object):
    def setupUi(self, Dialog5):
        Dialog5.setObjectName("Dialog5")
        Dialog5.resize(1000, 600)
        self.widget = QtWidgets.QWidget(Dialog5)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1051, 50))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:repeat, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(49, 77, 168, 255));")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 0, 191, 41))
        font = QtGui.QFont()
        font.setFamily("STCaiyun")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog5)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 351, 61))
        font = QtGui.QFont()
        font.setFamily("STHupo")
        font.setPointSize(22)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog5)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 201, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.Specialisebox5 = QtWidgets.QTextEdit(Dialog5)
        self.Specialisebox5.setGeometry(QtCore.QRect(270, 140, 601, 51))
        self.Specialisebox5.setObjectName("Specialisebox5")
        self.label_4 = QtWidgets.QLabel(Dialog5)
        self.label_4.setGeometry(QtCore.QRect(20, 230, 171, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Linkedinportfolio5 = QtWidgets.QTextEdit(Dialog5)
        self.Linkedinportfolio5.setGeometry(QtCore.QRect(300, 430, 571, 81))
        self.Linkedinportfolio5.setObjectName("Linkedinportfolio5")
        self.Next5 = QtWidgets.QPushButton(Dialog5)
        self.Next5.setGeometry(QtCore.QRect(480, 530, 100, 40))
        self.Next5.setObjectName("Next5")
        self.Languagedropdown5 = QtWidgets.QComboBox(Dialog5)
        self.Languagedropdown5.setGeometry(QtCore.QRect(270, 230, 281, 41))
        self.Languagedropdown5.setObjectName("Languagedropdown5")
        self.Languagedropdown5.addItem("")
        self.Languagedropdown5.addItem("")
        self.Languagedropdown5.addItem("")
        self.Languagedropdown5.addItem("")
        self.label_5 = QtWidgets.QLabel(Dialog5)
        self.label_5.setGeometry(QtCore.QRect(10, 420, 281, 31))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.textEdit = QtWidgets.QTextEdit(Dialog5)
        self.textEdit.setGeometry(QtCore.QRect(650, 200, 221, 191))
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(Dialog5)
        QtCore.QMetaObject.connectSlotsByName(Dialog5)

    def retranslateUi(self, Dialog5):
        _translate = QtCore.QCoreApplication.translate
        Dialog5.setWindowTitle(_translate("Dialog5", "Dialog"))
        self.label.setText(_translate("Dialog5", "<html><head/><body><p><span style=\" font-weight:600; font-style:italic; color:#ffffff;\">TalentMap</span></p></body></html>"))
        self.label_2.setText(_translate("Dialog5", "<html><head/><body><p><span style=\" font-size:26pt; font-weight:600; color:#314da8;\">Special Skills:</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog5", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#314da8;\">Specialise at: </span></p></body></html>"))
        self.Specialisebox5.setHtml(_translate("Dialog5", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>"))
        self.label_4.setText(_translate("Dialog5", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#314da8;\">Languages:</span></p><p><span style=\" font-size:18pt; font-weight:600;\"><br/></span></p></body></html>"))
        self.Next5.setText(_translate("Dialog5", "Next"))
        self.Languagedropdown5.setItemText(0, _translate("Dialog5", "English"))
        self.Languagedropdown5.setItemText(1, _translate("Dialog5", "Bengali"))
        self.Languagedropdown5.setItemText(2, _translate("Dialog5", "Chinese"))
        self.Languagedropdown5.setItemText(3, _translate("Dialog5", "Portugese"))
        self.label_5.setText(_translate("Dialog5", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; color:#314da8;\">Linkedin Portfolio:</span></p></body></html>"))
