# Form implementation generated from reading ui file 'f:\1-2 semester\hackathonimproved\hackathonImprovised\UI\CV2.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(643, 864)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(0, -20, 641, 871))
        self.label.setStyleSheet("background-image: url(:/newPrefix/cv1.jpg);")
        self.label.setObjectName("label")
        self.Name = QtWidgets.QLabel(Dialog)
        self.Name.setGeometry(QtCore.QRect(20, 250, 221, 91))
        self.Name.setText("")
        self.Name.setObjectName("Name")
        self.Ocupation = QtWidgets.QLabel(Dialog)
        self.Ocupation.setGeometry(QtCore.QRect(30, 370, 211, 41))
        self.Ocupation.setText("")
        self.Ocupation.setObjectName("Ocupation")
        self.Phone = QtWidgets.QLabel(Dialog)
        self.Phone.setGeometry(QtCore.QRect(90, 460, 151, 21))
        self.Phone.setText("")
        self.Phone.setObjectName("Phone")
        self.Mail = QtWidgets.QLabel(Dialog)
        self.Mail.setGeometry(QtCore.QRect(90, 485, 151, 21))
        self.Mail.setText("")
        self.Mail.setObjectName("Mail")
        self.Linkedin = QtWidgets.QLabel(Dialog)
        self.Linkedin.setGeometry(QtCore.QRect(90, 510, 151, 21))
        self.Linkedin.setText("")
        self.Linkedin.setObjectName("Linkedin")
        self.Address = QtWidgets.QLabel(Dialog)
        self.Address.setGeometry(QtCore.QRect(100, 540, 151, 41))
        self.Address.setText("")
        self.Address.setObjectName("Address")
        self.Profile = QtWidgets.QLabel(Dialog)
        self.Profile.setGeometry(QtCore.QRect(20, 630, 231, 141))
        self.Profile.setText("")
        self.Profile.setObjectName("Profile")
        self.Experience1 = QtWidgets.QLabel(Dialog)
        self.Experience1.setGeometry(QtCore.QRect(290, 110, 311, 121))
        self.Experience1.setText("")
        self.Experience1.setObjectName("Experience1")
        self.Experience2 = QtWidgets.QLabel(Dialog)
        self.Experience2.setGeometry(QtCore.QRect(290, 270, 321, 131))
        self.Experience2.setText("")
        self.Experience2.setObjectName("Experience2")
        self.Education1 = QtWidgets.QLabel(Dialog)
        self.Education1.setGeometry(QtCore.QRect(290, 480, 311, 81))
        self.Education1.setText("")
        self.Education1.setObjectName("Education1")
        self.Education2 = QtWidgets.QLabel(Dialog)
        self.Education2.setGeometry(QtCore.QRect(290, 590, 311, 91))
        self.Education2.setText("")
        self.Education2.setObjectName("Education2")
        self.Language = QtWidgets.QLabel(Dialog)
        self.Language.setGeometry(QtCore.QRect(290, 740, 311, 91))
        self.Language.setText("")
        self.Language.setObjectName("Language")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TextLabel"))
